services:
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: # vul dit zelf in.
            PGADMIN_DEFAULT_PASSWORD: # vul dit zelf in.
        ports:
            # bereikbaar via: http://localhost:5050
            - '5050:80'
        depends_on:
            - db

    db:
        image: postgres
        environment:
            POSTGRES_DB: PollenBackend
            POSTGRES_USER: # Vul dit zelf in
            POSTGRES_PASSWORD: # Vul dit zelf in
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pollenbackend:
        image: pollenbackend
        build:
            context: ./PollenBackend
            dockerfile: Dockerfile
        volumes:
            - ./PollenBackend:/app # Mount the local source code
            - pollenbackend_build:/app/bin # Persistent build artifacts
            - pollenbackend_obj:/app/obj # Persistent object files
        ports:
            - '5000:5000'
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - db
        command: dotnet watch run --urls=http://0.0.0.0:5000

volumes:
    postgres_data: {} # Volume for PostgreSQL data
    pollenbackend_build: {} # Volume for build artifacts
    pollenbackend_obj: {} # Volume for object files