version: '3.4'

services:
  pollenapi:
    image: pollenapi
    build:
      context: ./PollenApi
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: pollenapi
      POSTGRES_USER: # Vul dit zelf in
      POSTGRES_PASSWORD: # Vul dit zelf in
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
